-- MySQL Script generated by MySQL Workbench
-- Thu Mar 31 20:28:13 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema MiCuenta
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema MiCuenta
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `MiCuenta` DEFAULT CHARACTER SET utf8 ;
USE `MiCuenta` ;

-- -----------------------------------------------------
-- Table `MiCuenta`.`AsientoContables`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MiCuenta`.`AsientoContables` (
  `idAsientoContables` INT NOT NULL AUTO_INCREMENT,
  `Fecha` DATETIME NULL,
  `Descripcion` VARCHAR(45) NULL,
  `createdAt` DATETIME NULL,
  `updatedAt` DATETIME NULL,
  PRIMARY KEY (`idAsientoContables`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MiCuenta`.`Cuenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MiCuenta`.`Cuenta` (
  `idCuenta` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Tipo` VARCHAR(45) NOT NULL,
  `Debe` DECIMAL(8,5) NOT NULL,
  `Haber` DECIMAL(8,5) NOT NULL,
  `createdAt` DATETIME NULL,
  `updatedAt` DATETIME NULL,
  `idAsientoContables` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`idCuenta`),
  INDEX `fk_Cuenta_AsientoContables_idx` (`idAsientoContables` ASC),
  CONSTRAINT `fk_Cuenta_AsientoContables`
    FOREIGN KEY (`idAsientoContables`)
    REFERENCES `MiCuenta`.`AsientoContables` (`idAsientoContables`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MiCuenta`.`LibroMayors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MiCuenta`.`LibroMayors` (
  `idLibroMayors` INT NOT NULL AUTO_INCREMENT,
  `Detalle` VARCHAR(45) NULL,
  `SumaDebe` DECIMAL(8,5) NULL,
  `SumaHaber` VARCHAR(45) NULL,
  `createdAt` DATETIME NULL,
  `updatedAt` DATETIME NULL,
  `idAsientoContables` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`idLibroMayors`),
  INDEX `fk_LibroMayors_AsientoContables1_idx` (`idAsientoContables` ASC),
  CONSTRAINT `fk_LibroMayors_AsientoContables1`
    FOREIGN KEY (`idAsientoContables`)
    REFERENCES `MiCuenta`.`AsientoContables` (`idAsientoContables`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
